### ISSUE TITLE
my example does not work

### ISSUE THREAD

**Issue by Mexikaner9** [paulkr/quietflow.js#1]
Hello
I would like to use your script. The effects are really fantastic.
Unfortunately my example does not work. 
http://argomri.com/1000/ 
Can you please tell me what is wrong?
Thanks in advance
best regards
Chris

**Comment by paulkr** [comment]
Hi there! 

Thanks for reaching out. In your specific case, you have 2 options. 
Either start quietflow on a window.onload function or move your script code at the bottom of your <body> tag. For you, it would be after the closing div of the element with the ID "global". 

I hope everything works out!

**Comment by Mexikaner9** [comment]
Hi paulkr

thank you very much for your answer!
Now it works!
Your script is great. I really appreciate your work!

Perhaps the background effect on https://y7k.com/de is a effect you want to implement

Have a good time
best regards
Chris

**Comment by Mexikaner9** [comment]
or the effect on https://robertsspaceindustries.com/starmap as another version of squareFlash. Have a nice day

**Comment by Mexikaner9** [comment]
many effects you can find on http://njla.us/
